views:
  - output: "index.html"
    query: "index.rq"
    template: "index.html"
  - output: "{{slug}}/index.html"
    query: "services.rq"
    template: "service.html"
  - output: "sitemap.xml"
    query: "index.rq"
    template: "sitemap.xml"
    unsafe: true
